### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by Poussinou** [RodrigoDavy/Wii-U-Gamepad-Brute-Force-Sync#2]
Can you please tag your releases (see [here](https://help.github.com/articles/creating-releases/)), it would be helpful for the F-Droid release. You could also attach the binaries to your releases (see [here](https://blog.github.com/2013-07-02-release-your-software/)).

That's pretty easy and very helpful for those of us who aren't using Google services.

**Comment by IzzySoft** [comment]
Just wondering: the tagged release has version 1.1 (which implies there was a 1.0 before that) – but versionCode is still on "1". Please remember to increase that with each release, as that's what Android uses to identify versions (and accepting updates if the number is higher than what's already installed).

**Comment by RodrigoDavy** [comment]
Thanks, I just learned how versionCode works and I modified it. I'll be sure to always update it from now on :)
